apiVersion: v1
kind: Service
metadata:
  name: "moderation-website"
  labels:
    app: moderation-website
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: moderation-website
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "moderation-website"
  namespace: "default"
  labels:
    app: "moderation-website"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "moderation-website"
  template:
    metadata:
      labels:
        app: "moderation-website"
    spec:
      containers:
      - name: "moderation-website"
        image: "cyberdiscovery/moderation-website:latest"
        env:
        - name: "BOT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "BOT_TOKEN"
        - name: "MONGOHOST"
          value: "cyberdisc-db"
        - name: "DISCORDCLIENTID"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "FLASKSECRET"
        - name: "FLASKSECRET"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "FLASKSECRET"
        - name: "MONGOPORT"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "MONGOPORT"
        - name: "MONGODATABASE"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "MONGODATABASE"
        - name: "MONGOUSER"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "MONGOUSER"
        - name: "MONGOPASSWORD"
          valueFrom:
            secretKeyRef:
              name: "creds"
              key: "MONGOPASSWORD"
        ports:
        - containerPort: 80
          name: "moderation-website"
