trigger:
- master

pr: none

stages:
  - stage: Publish
    jobs:
      - job: PublishApplication
        displayName: Publish Application

        pool:
          vmImage: Ubuntu 18.04

        steps:
        - task: Docker@2
          displayName: 'Publish to Docker Hub'
          inputs:
            containerRegistry: 'Docker Hub'
            repository: cyberdiscovery/moderation-website
            Dockerfile: '$(System.DefaultWorkingDirectory)/Dockerfile'
            tags: latest

        - task: Docker@2
          displayName: 'Publish to GitHub Packages'
          inputs:
            containerRegistry: 'GitHub Packages'
            repository: 'CyberDiscovery/moderation-website/moderation-website'
            tags: latest
  
  - stage: Deploy
    jobs:
      - job: Deploy
        displayName: Deploy

        pool:
          vmImage: Ubuntu 18.04

        steps:
        - task: Kubernetes@1
          displayName: 'Delete Old Deployment'
          inputs:
            kubernetesServiceEndpoint: 'Kubernetes Environment-default-1587170276979'
            command: delete
            arguments: 'deployment.extensions/quotes-website'
            versionSpec: 1.15.0

        - task: Kubernetes@1
          displayName: 'Deploy to Google Kubernetes Engine'
          inputs:
            kubernetesServiceEndpoint: 'Kubernetes Environment-default-1587170276979'
            command: apply
            useConfigurationFile: true
            configuration: '$(System.DefaultWorkingDirectory)/deployment.yaml'
            secretType: generic
            forceUpdate: false
            versionSpec: 1.15.0
